build:
  test:
    image: hseeberger/scala-sbt
    commands:
      - sbt test -Dsbt.ivy.home=/drone/.ivy

  build:
    image: hseeberger/scala-sbt
    commands:
      - sbt core/assembly -Dsbt.ivy.home=/drone/.ivy
      - mv core/target/scala-2.11/metarpheus-assembly-0.1.0.jar metarpheus.jar
    when:
      event: tag

publish:
  github_release:
    api_key: $$GITHUB_TOKEN
    files: metarpheus.jar

cache:
  mount:
    - /drone/.ivy
