build:
  test:
    image: hseeberger/scala-sbt
    commands:
      - cd extractor
      - sbt test -Dsbt.ivy.home=/drone/.ivy

  build:
    image: hseeberger/scala-sbt
      - cd extractor
      - sbt assembly -Dsbt.ivy.home=/drone/.ivy
      - mv target/scala-2.11/metarpheus-assembly-0.0.1-SNAPSHOT.jar metarpheus.jar

publish:
  github_release:
    api_key: $$GITHUB_TOKEN
    files: extractor/metarpheus.jar
    checksum: sha1

cache:
  mount:
    - /drone/.ivy
