build:
  test:
    image: hseeberger/scala-sbt
    commands:
      - sbt coreJVM/test -Dsbt.ivy.home=/drone/.ivy
      - sbt cli/test -Dsbt.ivy.home=/drone/.ivy

  build:
    image: hseeberger/scala-sbt
    commands:
      - sbt cli/assembly -Dsbt.ivy.home=/drone/.ivy
      - mv cli/target/scala-2.12/metarpheus-cli-assembly-$$TAG.jar metarpheus.jar
    when:
      event: tag

publish:
  github_release:
    api_key: $$GITHUB_TOKEN
    files: metarpheus.jar

cache:
  mount:
    - /drone/.ivy
